[package]
name = "shield-tower"
description = "Tower integration for Shield."

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
http.workspace = true
shield = { path = "../../core/shield" }
tower-layer.workspace = true
tower-service.workspace = true
tower-sessions.workspace = true
